### PR TITLE
Update gps.conf

### PR DESCRIPTION
**Pull request by arshad-run**

### CODE REVIEW

**Comment by AlvaroBrey** [comment]
What is this for? Does it improve gps in any way?

**Comment by arshad-run** [comment]
i take it from google marlin. maybe will improve gps. must try

**Comment by arshad-run** [comment]
I also make some pull request on davidevinavil github. please take a look : https://github.com/davidevinavil/android_device_zuk_z2_plus/pulls .

**Comment by AlvaroBrey** [comment]
Unless there's a reason to think it will improve anything, I won't merge anything or bother testing it. *You* should test it before PRing.

**Pull request closed without merging**
