### PR TITLE
Portuguese strings.xml

### PR DESCRIPTION
**Pull request by jtnmartinho**
U-Touch settings translated to Portuguese from Portugal (can be applied to Brazilian Portuguese, and other Portuguese alternatives).

### CODE REVIEW

**Comment by AlvaroBrey** [comment]
Hello and thanks for your contribution! :)

There is a slight issue with this commit. the `res/values` folder is for the default translation (english). This file should go in a folder called `res/values-pt`. If you can change that, I will merge this PR.

You can look at #1 for an example.

If you don't want to do it, that's alright, I'll just commit the strings myself.

Thank you!

**Comment by jtnmartinho** [comment]
Hi!

You're welcomed! : )

Please check if it's ok now. It's my first time doing something like this.

Thanks for you amazing work!

Take care,
J

**Comment by AlvaroBrey** [comment]
It's *almost* ok. You need to undo the changes to `res/values/strings.xml`, so that only the changes in `values-pt` remain.

Cheers!

**Comment by jtnmartinho** [comment]
Sorry for all my mistakes. Please check if it's ok now.

**Comment by AlvaroBrey** [comment]
Nope, now you've deleted the file, instead of undoing the changes. Try this:
```
git checkout origin/cm-14.1 --  (path omitted)/res/values/strings.xml
git add .
git commit -m 'Undo changes to default translations'
git push
```
Hint: in the pull request window, you can check the "Files changed" tab to see what's changed from the cm-14.1 branch to your branch. The only thing there should be a new file. Now it shows a new file and a deleted one.

In any case, if you don't manage or if it's too complicated I can just add them for you.

**Comment by jtnmartinho** [comment]
Hi!

I had trouble following you tips. Hope this time I put the file where it's needed. If not, can you please do it yourself? Thanks! : )

Take care,
J

**Comment by AlvaroBrey** [comment]
Closed as it's been replaced by #4.

**Pull request closed without merging**
